controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
deletec:
    path: /computer/deletec/{id}
    controller: App\Controller\ComputerController::delete
fetch:
    path: /computer/fetch/
    controller: App\Controller\ComputerController::fetchcat
